version: "3.8"

services:

  db:
    image: postgres:15
    shm_size: 2Gb
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=512'
      - '-c'
      - 'shared_buffers=2GB'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: crawler
      POSTGRES_DB: page_crawls
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql/data/

  mq:
    image: rabbitmq:3-management-alpine
    # environment:
    #   RABBITMQ_VM_MEMORY_HIGH_WATERMARK: '0.65'
    ports:
      - "5672:5672"
      - "15672:15672" # managment ui http://localhost:15672/
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia

  visited:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  jaeger:
    image: jaegertracing/all-in-one:1.46
    ports:
     # - 5775:5775/udp
     - 6831:6831/udp
     - 6832:6832/udp
     - 5778:5778   # configuration
     - 16686:16686 # frontend http://localhost:16686/
     - 14250:14250
     - 14268:14268 # traces api
     - 14269:14269
     #- 9411:9411 # zipkin
    environment:
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_REPORTER_LOG_SPANS=true
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - SPAN_STORAGE_TYPE=badger  # default is 'memory'
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/var/lib/badger/data
      - BADGER_DIRECTORY_KEY=/var/lib/badger/key
    volumes:
      - jaeger-badger:/var/lib/badger

  crawler:
    image: remora-crawler:latest
    build:
      context: .
      target: crawler-api
    command: ["-port", "3010"]
    volumes:
      - ./config/config.yml:/var/local/remora/config.yml:ro
    ports:
      - "3010:3010"
    restart: on-failure

  # graph-api:
  #   image: remora-api:latest
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: .
  #     target: api
  #   command: ["-p", "8080"]
  #   network_mode: host
  #   # Volume is overridden in prod
  #   volumes:
  #     - ./config/config.yml:/var/local/remora/config.yml:ro
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped

  #crawler:
  #  image: remora:latest
  #  build:
  #    dockerfile: ./Dockerfile
  #    context: .
  #    target: remora
  #  network_mode: host
  #  command: ["spider", "en.wikipedia.org"]
  #  # Volume is overridden in prod
  #  volumes:
  #    - ./config/config.yml:/var/local/remora/config.yml:ro

volumes:
  postgres:
  rabbitmq:
  redis:
  jaeger-badger:

configs:
  remora.yml:
    file: ./remora.yml
