version: "3.8"

services:
  db:
    image: postgres:13.3-alpine
    container_name: remora-db
    shm_size: 2Gb
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=512'
      - '-c'
      - 'shared_buffers=2GB'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: crawler
      POSTGRES_DB: page_crawls
    restart: unless-stopped
    ports:
      - target: 5432
        published: 55432
        protocol: tcp
        mode: bridge
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d:ro
      # - ./db/data:/var/lib/postgresql/data/
    networks:
      - backend

  redis:
    image: redis:6.2.4-alpine
    container_name: visited-set
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - backend

  mq:
    image: rabbitmq:3-management-alpine
    container_name: remora-msgq
    restart: unless-stopped
    # environment:
    #  RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.65
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: bridge
      - target: 15672
        published: 15672
        protocol: tcp
        mode: bridge
    # volumes:
      # - ~/.docker-conf/rabbitmq/:/var/lib/rabbitmq/
    networks:
      - backend

  crawler:
    image: remora:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: remora-crawler
    command: ["help"]
    volumes:
      - remora-config:/var/local/remora
    networks:
      - backend

  search:
   image: solr:8.9.0
   container_name: remora-search
   restart: unless-stopped
   ports:
     - "8983:8983"

networks:
  backend:
    driver: bridge

volumes:
  remora-config:

