version: "3.8"

services:
  db:
    image: postgres:13.3-alpine
    container_name: diktyo-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: varys # yes, from Game of Thrones
      POSTGRES_DB: diktyo
    restart: unless-stopped
    ports:
      - target: 5432
        published: 55432
        protocol: tcp
        mode: bridge
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: diktyo-msgq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

