version: "3.8"

services:
  db:
    image: postgres:13.3-alpine
    container_name: diktyo-db
    command: ['postgres', '-c', 'max_connections=256', '-c', 'shared_buffers=328MB']
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: varys # yes, from Game of Thrones
      POSTGRES_DB: diktyo
    restart: unless-stopped
    ports:
      - target: 5432
        published: 55432
        protocol: tcp
        mode: bridge
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d:ro
      - ./db/data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2.4-alpine
    container_name: visited-set
    ports:
      - 6379:6379
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: diktyo-msgq
    restart: unless-stopped
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: bridge
      - target: 15672
        published: 15672
        protocol: tcp
        mode: bridge
    volumes:
      - ~/.docker-conf/rabbitmq/:/var/lib/rabbitmq/

  remora:
    image: remora:0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "test-crawler"
    command:
      - 'deinopis'
      - '--host'
      - 'en.wikipedia.org'
    network_mode: host
    volumes:
      - /var/local/diktyo:/var/local/diktyo
