version: "3.8"

services:
  graph-api:
    volumes:
      - remora-config:/var/local/remora:ro
  crawler-api:
    volumes:
      - remora-config:/var/local/remora:ro
  mq:
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/
  #crawler:
  #  volumes:
  #    - remora-config:/var/local/remora:ro
