// This program is meant purely to build the standard library and speed up
// docker image builds.
package main

import (
	_ "bufio"
	_ "bytes"
	_ "compress/gzip"
	_ "context"
	_ "database/sql"
	_ "database/sql/driver"
	_ "encoding/gob"
	_ "encoding/hex"
	_ "encoding/json"
	_ "encoding/xml"
	_ "errors"
	_ "fmt"
	_ "hash"
	_ "hash/fnv"
	_ "io"
	_ "log"
	_ "net"
	_ "net/http"
	_ "net/http/pprof"
	_ "net/url"
	_ "os"
	_ "os/exec"
	_ "os/signal"
	_ "path"
	_ "path/filepath"
	_ "reflect"
	_ "regexp"
	_ "runtime"
	_ "runtime/pprof"
	_ "sort"
	_ "strconv"
	_ "strings"
	_ "sync"
	_ "sync/atomic"
	_ "syscall"
	_ "time"

	_ "github.com/PuerkitoBio/goquery"
	_ "github.com/dgraph-io/badger/v3"
	_ "github.com/go-redis/redis"
	_ "github.com/harrybrwn/config"
	_ "github.com/lib/pq"
	_ "github.com/pkg/errors"
	_ "github.com/sirupsen/logrus"
	_ "github.com/spf13/cobra"
	_ "github.com/spf13/pflag"
	_ "github.com/streadway/amqp"
	_ "github.com/temoto/robotstxt"
	_ "golang.org/x/net/html"
	_ "golang.org/x/net/html/atom"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	_ "google.golang.org/protobuf/runtime/protoimpl"
	_ "gopkg.in/natefinch/lumberjack.v2"
)

func main() {}
