// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: page_request.proto

package web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PageRequest is a request for the crawler to crawl a webpage.
type PageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL is the url to be crawled.
	URL string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	// Key is the routing key that might optionally be used to deturmine which
	// web crawler the request will go to.
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Depth is the crawl depth of the request.
	Depth uint32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	// Retry is a counter for the number of retries for fetching the webpage.
	Retry         int32 `protobuf:"varint,4,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_page_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_page_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_page_request_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *PageRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PageRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *PageRequest) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

var File_page_request_proto protoreflect.FileDescriptor

const file_page_request_proto_rawDesc = "" +
	"\n" +
	"\x12page_request.proto\x12\x03web\"]\n" +
	"\vPageRequest\x12\x10\n" +
	"\x03URL\x18\x01 \x01(\tR\x03URL\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\rR\x05depth\x12\x14\n" +
	"\x05retry\x18\x04 \x01(\x05R\x05retryb\x06proto3"

var (
	file_page_request_proto_rawDescOnce sync.Once
	file_page_request_proto_rawDescData []byte
)

func file_page_request_proto_rawDescGZIP() []byte {
	file_page_request_proto_rawDescOnce.Do(func() {
		file_page_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_page_request_proto_rawDesc), len(file_page_request_proto_rawDesc)))
	})
	return file_page_request_proto_rawDescData
}

var file_page_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_page_request_proto_goTypes = []any{
	(*PageRequest)(nil), // 0: web.PageRequest
}
var file_page_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_page_request_proto_init() }
func file_page_request_proto_init() {
	if File_page_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_page_request_proto_rawDesc), len(file_page_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_page_request_proto_goTypes,
		DependencyIndexes: file_page_request_proto_depIdxs,
		MessageInfos:      file_page_request_proto_msgTypes,
	}.Build()
	File_page_request_proto = out.File
	file_page_request_proto_goTypes = nil
	file_page_request_proto_depIdxs = nil
}
